import Link from 'next/link'
import { getWorkspace } from '@/lib/workspace'
export default async function Home(){
 const {supabase,org,company}=await getWorkspace(); const profile=Array.isArray((company as any).company_profiles)?(company as any).company_profiles[0]:(company as any).company_profiles
 const [{count:contentCount},{count:campaignCount},{data:wallet},{data:sub}] = await Promise.all([
  supabase.from('content_items').select('*',{count:'exact',head:true}).eq('company_id',company!.id),
  supabase.from('campaigns').select('*',{count:'exact',head:true}).eq('company_id',company!.id),
  supabase.from('credit_wallets').select('balance').eq('organization_id',org!.id).maybeSingle(),
  supabase.from('subscriptions').select('plan,status,trial_ends_at').eq('organization_id',org!.id).maybeSingle()
 ])
 return <><div className="page-head"><div><div className="eyebrow">MTK DIGITAL AI</div><h1>Olá, {company!.name} 👋</h1><p className="muted">Seu marketing, organizado em um único lugar.</p></div><div className="plan-pill">{sub?.plan?.toUpperCase()||'TRIAL'} · {wallet?.balance??0} créditos</div></div><div className="card hero"><div><div className="muted">Seu objetivo principal</div><h2>{company!.primary_goal||'Crescer seu negócio'}</h2><p>{company!.city?`${company!.city}${company!.state?` — ${company!.state}`:''}`:'Atendimento digital e local'}</p></div><div className="ai-reco"><b>✨ Recomendação da MTK AI</b><p>{profile?.next_action||'Crie sua primeira campanha de marketing.'}</p><Link href="/campanhas"><button className="btn gold">CRIAR CAMPANHA →</button></Link></div></div><div className="grid stats"><div className="card"><div className="big">{profile?.mtk_score??70}</div><div className="muted">MTK Score</div></div><div className="card"><div className="big">{contentCount??0}</div><div className="muted">Conteúdos criados</div></div><div className="card"><div className="big">{campaignCount??0}</div><div className="muted">Campanhas</div></div><div className="card"><div className="big">{wallet?.balance??0}</div><div className="muted">Créditos restantes</div></div></div><div className="grid content2"><div className="card"><h2>DNA Digital</h2><div className="dna"><div><span>Segmento</span><b>{company!.segment}</b></div><div><span>Público</span><b>{profile?.audience||'A definir'}</b></div><div><span>Tom</span><b>{Array.isArray(profile?.tone)?profile.tone.join(' + '):'Profissional'}</b></div><div><span>Oferta principal</span><b>{profile?.main_offer||'A definir'}</b></div></div></div><div className="card"><h2>Ações rápidas</h2><div className="quick"><Link href="/criar"><button className="btn">Criar conteúdo</button></Link><Link href="/campanhas"><button className="btn">Campanha</button></Link><Link href="/calendario"><button className="btn">Calendário</button></Link></div></div></div></>
}
